version: '3.9'

services:
  mongodb:
    image: mongo:5.0.8
    container_name: ${APP_COMPOSE_PROJECT_NAME}_mongodb
    restart: always
    volumes:
      - mongodb-micro-data:/data/db
    environment:
      - MONGODB_ROOT_USER=${MONGODB_ROOT_USER}
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
    ports:
      - 27017:27017

volumes:
  mongodb-micro-data:
    driver: local
