version: '3.9'

services:
  mongodb:
    image: mongo:5.0.8
    container_name: ${APP_PROJECT_NAME}_mongodb
    restart: always
    volumes:
      - mongodb-micro-manager-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
    ports:
      - "27017:27017"

volumes:
  mongodb-micro-manager-data:
    driver: local
